// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iezocuwkqexxbmapdjmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllem9jdXdrcWV4eGJtYXBkam1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNTA2MzUsImV4cCI6MjA3MDgyNjYzNX0.7tuz2fZ8R7S-LYMsNWYpsyfq2G4yurtxXDji8FYi5FM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});